envs:
  - name: RemoteEnv
    n_envs: 10000
    data_source: navigation
    seed: [0, 30]
    max_turns: 10
    response_length_per_turn: 512
    config:
      base_urls: "http://localhost:8000"
      timeout: 120
      retries: 3
      eval_set: base
      prompt_format: eval_mode
      max_actions_per_step: 5
